[[bond]]
source = "tpknam1qq82qkjpeznlf06r7clf70z8hss537dhls7w9u5067xztlrcfxvsgqft5cc"
validator = "tnam1qy6y8ws67ks2p5jl53s6yukre554mhwrugdp8vjh"
amount = "400"

[bond.signatures]
tpknam1qq82qkjpeznlf06r7clf70z8hss537dhls7w9u5067xztlrcfxvsgqft5cc = "signam1qr72gzvsvnj7pgwekpz0jp798hme87y2pzxqx446ectjecjfnejw4wleww59p665ywvxrmy9f9yfy2czgszth43c3ka7usvd6c3hrycd02aju3"


[[bond]]
source = "tpknam1qq82qkjpeznlf06r7clf70z8hss537dhls7w9u5067xztlrcfxvsgqft5cc"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "100"

[bond.signatures]
tpknam1qq82qkjpeznlf06r7clf70z8hss537dhls7w9u5067xztlrcfxvsgqft5cc = "signam1qztlqh5ydvcgyn9an5wm9wy2jyvwdw5hzzh977pz73fgyr6tnjg3mc6ngs7g860r448ek46lxzfqn0rfjkpjpeae05s6xzdzlamq8xs2vp4paw"


